In [1]:
import numpy as np

## numpy array

In [2]:
benimListem = [20,30,40]
type(benimListem)

list

In [4]:
type(np.array(benimListem))

numpy.ndarray

In [5]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
type(matrixListesi)

list

In [8]:
matrixListesi[1][0]

20

In [9]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace
#en sağa yazdığım değer, stopladığım index'e kadar hepsinin arasında eşit mesafe olan sayı dizisi yaz

In [22]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [27]:
np.linspace(1,100,123) #MESELA YANİ

array([  1.        ,   1.81147541,   2.62295082,   3.43442623,
         4.24590164,   5.05737705,   5.86885246,   6.68032787,
         7.49180328,   8.30327869,   9.1147541 ,   9.92622951,
        10.73770492,  11.54918033,  12.36065574,  13.17213115,
        13.98360656,  14.79508197,  15.60655738,  16.41803279,
        17.2295082 ,  18.04098361,  18.85245902,  19.66393443,
        20.47540984,  21.28688525,  22.09836066,  22.90983607,
        23.72131148,  24.53278689,  25.3442623 ,  26.1557377 ,
        26.96721311,  27.77868852,  28.59016393,  29.40163934,
        30.21311475,  31.02459016,  31.83606557,  32.64754098,
        33.45901639,  34.2704918 ,  35.08196721,  35.89344262,
        36.70491803,  37.51639344,  38.32786885,  39.13934426,
        39.95081967,  40.76229508,  41.57377049,  42.3852459 ,
        43.19672131,  44.00819672,  44.81967213,  45.63114754,
        46.44262295,  47.25409836,  48.06557377,  48.87704918,
        49.68852459,  50.5       ,  51.31147541,  52.12

## eye

In [33]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [36]:
np.random.randn(8)

array([-0.12417972, -2.0677711 , -0.90873647,  0.09486487, -0.63060585,
        1.58564277,  0.38163125, -0.83357776])

In [37]:
np.random.randn(4,4)

array([[-0.03713179,  0.9504934 ,  0.64136602, -0.60826913],
       [-1.05512438, -1.22327633, -1.68191676, -0.98606512],
       [-0.46697516, -2.11504232,  0.30494538, -0.39883125],
       [ 0.32417344, -0.2823509 ,  0.76552197, -1.30570065]])

In [47]:
np.random.randint(1,10)

4

In [49]:
np.random.randint(1,300,5)

array([ 94, 124, 193, 213,  49])

In [50]:
benimNumpyDizim = np.arange(30)

In [52]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [74]:
benimRandomDizim = np.random.randint(0,100,20)

In [75]:
benimRandomDizim

array([98, 81,  5, 64, 99,  4, 21,  4,  2, 49, 74, 62, 96, 50, 56, 89,  2,
       74, 48, 28])

## numpy dizi methodları

In [76]:
benimNumpyDizim.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [77]:
benimNumpyDizim.max()

29

In [78]:
benimRandomDizim.max()

99

In [79]:
benimRandomDizim.min()

2

In [80]:
benimRandomDizim.argmax()

4

In [81]:
benimRandomDizim.argmin()

8

In [85]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
reshapeDizim= benimNumpyDizim.reshape(5,6)

In [87]:
reshapeDizim.shape

(5, 6)