In [1]:
import numpy as np

In [16]:
benimDizim= np.arange(0,15)
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
benimDizim[5]

5

In [17]:
benimDizim[3:5]

array([3, 4])

In [20]:
benimDizim[3:8] = -5

In [21]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [22]:
baskaDizi = np.arange(0,24)

In [23]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
slicingDizisi = baskaDizi[4:9]

In [49]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [50]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [53]:
slicingDizisi[:] = 700

In [54]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [64]:
ornekDizi = np.arange(0,24)

In [65]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
ornekDiziKopyasi = ornekDizi.copy()

In [69]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [70]:
ornekDiziKopyaSlicing[:] = 800

In [71]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [73]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [74]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [76]:
benimMatrixDizim = np.array(benimListem)

In [77]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [78]:
benimMatrixDizim[0]

array([10, 20, 30])

In [79]:
benimMatrixDizim[1][2]

40

In [80]:
benimMatrixDizim[1,2]

40

In [81]:
benimMatrixDizim[1,2]

40

In [86]:
benimMatrixDizim[1:,1:]

array([[30, 40],
       [50, 60]])

In [87]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [88]:
yeniMatrix = np.array(yeniListe)

In [89]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [99]:
yeniBirDizi = np.random.randint(1,100,20)

In [100]:
yeniBirDizi

array([25, 35, 33,  9, 93, 81, 57, 84,  4, 89, 71,  3, 20,  1, 94, 52, 48,
       67, 69,  6])

In [101]:
yeniBirDizi > 24

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False, False, False,  True,  True,  True,  True,
        True, False])

In [102]:
yeniBirDizi

array([25, 35, 33,  9, 93, 81, 57, 84,  4, 89, 71,  3, 20,  1, 94, 52, 48,
       67, 69,  6])

In [103]:
sonucDizisi = yeniBirDizi > 24

In [104]:
sonucDizisi

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False, False, False,  True,  True,  True,  True,
        True, False])

In [105]:
yeniBirDizi

array([25, 35, 33,  9, 93, 81, 57, 84,  4, 89, 71,  3, 20,  1, 94, 52, 48,
       67, 69,  6])

In [106]:
yeniBirDizi[sonucDizisi]

array([25, 35, 33, 93, 81, 57, 84, 89, 71, 94, 52, 48, 67, 69])

In [107]:
yeniBirDizi

array([25, 35, 33,  9, 93, 81, 57, 84,  4, 89, 71,  3, 20,  1, 94, 52, 48,
       67, 69,  6])

In [109]:
yeniBirDizi[yeniBirDizi > 24]

array([25, 35, 33, 93, 81, 57, 84, 89, 71, 94, 52, 48, 67, 69])

In [110]:
sonDizi = np.arange(0,24)

In [111]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [112]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [113]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [114]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [115]:
sonDizi / sonDizi

/var/folders/ks/svk1bw8n1hvfwn8n5hzd_m000000gn/T/ipykernel_5928/1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [117]:
np.sqrt(sonDizi) #karekök alma

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [118]:
np.max(sonDizi)

23

In [119]:
np.min(sonDizi)

0